export const userData = [
  {
    id: 1,
    name: "Terry",
    age: 50,
    email: "atuny0@sohu.com",
  },
  {
    id: 2,
    name: "Sheldon",
    age: 28,
    email: "hbingley1@plala.or.jp",
  },
  {
    id: 3,
    name: "Terrill",
    age: 38,
    email: "rshawe2@51.la",
  },
  {
    id: 4,
    name: "Miles",
    age: 49,
    email: "yraigatt3@nature.com",
  },
  {
    id: 5,
    name: "Mavis",
    age: 38,
    email: "kmeus4@upenn.edu",
  },
  {
    id: 6,
    name: "Alison",
    age: 21,
    email: "jtreleven5@nhs.uk",
  },
  {
    id: 7,
    name: "Oleta",
    age: 31,
    email: "dpettegre6@columbia.edu",
  },
  {
    id: 8,
    name: "Ewell",
    age: 29,
    email: "ggude7@chron.com",
  },
  {
    id: 9,
    name: "Demetrius",
    age: 22,
    email: "nloiterton8@aol.com",
  },
  {
    id: 10,
    name: "Eleanora",
    age: 37,
    email: "umcgourty9@jalbum.net",
  },
  {
    id: 11,
    name: "Marcel",
    age: 39,
    email: "acharlota@liveinternet.ru",
  },
  {
    id: 12,
    name: "Assunta",
    age: 42,
    email: "rhallawellb@dropbox.com",
  },
  {
    id: 13,
    name: "Trace",
    age: 26,
    email: "lgribbinc@posterous.com",
  },
  {
    id: 14,
    name: "Enoch",
    age: 21,
    email: "mturleyd@tumblr.com",
  },
  {
    id: 15,
    name: "Jeanne",
    age: 26,
    email: "kminchelle@qq.com",
  },
  {
    id: 16,
    name: "Trycia",
    age: 41,
    email: "dpierrof@vimeo.com",
  },
  {
    id: 17,
    name: "Bradford",
    age: 43,
    email: "vcholdcroftg@ucoz.com",
  },
  {
    id: 18,
    name: "Arely",
    age: 42,
    email: "sberminghamh@chron.com",
  },
  {
    id: 19,
    name: "Gust",
    age: 46,
    email: "bleveragei@so-net.ne.jp",
  },
  {
    id: 20,
    name: "Lenna",
    age: 41,
    email: "aeatockj@psu.edu",
  },
  {
    id: 21,
    name: "Doyle",
    age: 23,
    email: "ckensleyk@pen.io",
  },
  {
    id: 22,
    name: "Tressa",
    age: 41,
    email: "froachel@howstuffworks.com",
  },
  {
    id: 23,
    name: "Felicity",
    age: 46,
    email: "beykelhofm@wikispaces.com",
  },
  {
    id: 24,
    name: "Jocelyn",
    age: 19,
    email: "brickeardn@fema.gov",
  },
  {
    id: 25,
    name: "Edwina",
    age: 21,
    email: "dfundello@amazon.co.jp",
  },
  {
    id: 26,
    name: "Griffin",
    age: 35,
    email: "lgronaverp@cornell.edu",
  },
  {
    id: 27,
    name: "Piper",
    age: 47,
    email: "fokillq@amazon.co.jp",
  },
  {
    id: 28,
    name: "Kody",
    age: 28,
    email: "xisherwoodr@ask.com",
  },
  {
    id: 29,
    name: "Macy",
    age: 45,
    email: "jissetts@hostgator.com",
  },
  {
    id: 30,
    name: "Maurine",
    age: 31,
    email: "kdulyt@umich.edu",
  },
];
